######################
# Params for the rendered introductory slide.
######################

[project]
size   = "1280x720"
server = "https://jreades.github.io/fsds/lectures"
audio  = "audio_src/"
cuts   = "lessons.md"

[outputs]
audio  = "_m4a"
video  = "_mp4"
slides = "_png"
merge  = "_mrg"
final  = "_output"

[intro]
name   = "intro.mp4"
length = 4.0
talk   = "Lecture Title"

[lessons.1]
title    = "The Basics\n(Part 1)"
subtitle = "Data Science for All"
track    = "Python the Basics-1"
week     = 2
sequence = 1

[lessons.4]
title    = "Iteration"
subtitle = "Data Science for All"
track    = "Iteration"
week     = 2
sequence = 4
